### ISSUE TITLE
Add Element Tag Support

### ISSUE THREAD

**Issue by TheConnMan** [Netuitive/zorka#14]
Element Tag classes exist in the library, but can not be added to the incoming elements.

**Comment by TheConnMan** [comment]
@Createor Do you want to add these through a `-D` property? Something like:
```
-Delement.tags=name:value,second:other
```

**Comment by Grumblesmith** [comment]
I had assumed this would be through the zorka.properties, like other agents. Having either option would likely be the ideal solution.

**Comment by TheConnMan** [comment]
Gotcha. I think putting them in the properties means it can be overridden from the runtime args.
